# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ca
                                 A QGIS plugin
 Assistant service CA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-02
        copyright            : (C) 2022 by Romain Lagrange - PCE Services
        email                : romain.lagrange@pceservices.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ca class from file ca.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ca import ca
    return ca(iface)
